### ISSUE TITLE
Switch to the 4th version of the API

### ISSUE THREAD

**Issue by mgol** [clarkbox/testswarm-browserstack#43]
BrowserStack has now the 4th version of the API; the only difference is that v3 was http whereas v4 is https.

This is blocked on https://github.com/scottgonzalez/node-browserstack/issues/32

**Comment by mzgol** [comment]
This is no longer blocked, the [browserstack](https://www.npmjs.com/package/browserstack) module supports the 4th version of the API.

**Comment by mgol** [comment]
PR: #46
